// Ported from opinion_cards.py and culture_cards.py
// Stable integer IDs are index-based

const opinionCards = [
  { id: 0, text: "WHICH DELIVERED\nTHE MOST VALUE?" },
  { id: 1, text: "WHICH WOULD YOU\nDEMO TO THE CEO?" },
  { id: 2, text: "WHICH WOULD YOU\nCUT FIRST?" },
  { id: 3, text: "WHICH SHOULD HAVE\nBEEN AN EMAIL?" },
  { id: 4, text: "WHICH ESTIMATE\nWAS MOST WRONG?" },
  { id: 5, text: "WHICH TOOK THE MOST\nMEETINGS TO SHIP?" },
  { id: 6, text: "WHICH IS MOST LIKELY\nTO PAGE YOU AT 2AM?" },
  { id: 7, text: "WHICH WOULD YOU\nDO AGAIN\nNEXT SPRINT?" },
  { id: 8, text: "WHICH WOULD YOU\nHAND OFF TO\n___________?" },
  { id: 9, text: "WHICH WOULD YOU\nNAME YOUR BAND\nAFTER?" },
];

const cultureCards = [
  { id: 0, title: "TECHNICAL DEBT", description: "The mortgage on your\ncodebase. You know you\nshould pay it down. You won't." },
  { id: 1, title: "DAILY STANDUP", description: "Fifteen minutes of everyone\nsaying they're not blocked\nwhile being very blocked." },
  { id: 2, title: "VELOCITY", description: "A number that goes up\nwhen things go well and gets\nblamed when they don't." },
  { id: 3, title: "DEFINITION OF DONE", description: "The checklist you agreed on\nin planning and quietly\nignore by Thursday." },
  { id: 4, title: "STORY POINTS", description: "A unit of effort that means\nnothing and everything\nat the same time." },
  { id: 5, title: "RETROSPECTIVE", description: "Where the team agrees to fix\nthe same three problems\nit agreed to fix last sprint." },
  { id: 6, title: "PRODUCT BACKLOG", description: "A graveyard of good ideas,\northogonal priorities,\nand stakeholder whims. RIP." },
  { id: 7, title: "SPRINT GOAL", description: "Written optimistically\non Monday.\nAbandoned by Wednesday." },
  { id: 8, title: "PI PLANNING", description: "Two days of sticky notes,\nsnacks, and collective\ndelusion at scale." },
  { id: 9, title: "ACCEPTANCE CRITERIA", description: "What 'done' means\nto stakeholders. Subject to\nreinterpretation upon demo." },
  { id: 10, title: "AGILE COACH", description: "A guide, a mirror, a Jedi.\nMostly just someone\nthe team learns to ignore." },
  { id: 11, title: "ART SYNC", description: "Where all teams pretend\ntheir dependencies\nare under control." },
  { id: 12, title: "BACKLOG REFINEMENT", description: "Grooming stories\nyou'll never build\nfor estimates that won't hold." },
  { id: 13, title: "BUG BASH", description: "Everyone finds bugs\nfor two hours.\nThen everyone goes home." },
  { id: 14, title: "BURN-DOWN CHART", description: "Starts hopeful.\nEnds in a conversation\nabout scope. Always." },
  { id: 15, title: "BURN-UP CHART", description: "Like a burn-down chart\nbut you frame the pain\nas progress instead." },
  { id: 16, title: "CAPACITY PLANNING", description: "Careful calculation\nof how much you can do,\nthen doing more anyway." },
  { id: 17, title: "CHANGE REQUEST", description: "Stakeholder for:\n'I know we agreed, but\nwhat if we didn't?'" },
  { id: 18, title: "CONTINUOUS INTEGRATION", description: "A pipeline that catches\nyour mistakes\nbefore your teammates do." },
  { id: 19, title: "CONTINUOUS DEPLOYMENT", description: "Shipping code so often\nyou read the alerts\nover breakfast." },
  { id: 20, title: "CROSS-FUNCTIONAL TEAM", description: "Everyone's job is\neveryone's job.\nSomehow nothing gets done." },
  { id: 21, title: "DEPENDENCIES", description: "The things blocking you\nthat you discovered\nduring the demo." },
  { id: 22, title: "DEPLOYMENT PIPELINE", description: "The automated obstacle course\nbetween your code\nand production." },
  { id: 23, title: "DESIGN THINKING", description: "Five sticky-note phases\nto solve problems\nyou already knew existed." },
  { id: 24, title: "DEVELOPER EXPERIENCE", description: "The art of keeping devs\nhappy enough\nnot to quit." },
  { id: 25, title: "DOG-FOODING", description: "Using your own product\nuntil you find all the bugs\nyour users already reported." },
  { id: 26, title: "EPIC", description: "A story too big\nfor a sprint.\nOr a quarter. Or a year." },
  { id: 27, title: "FEATURE FLAG", description: "A light switch for code.\nToggled on for one user.\nForgotten forever." },
  { id: 28, title: "FIBONACCI SEQUENCE", description: "Nature's perfect spiral.\nAlso how we pretend\nuncertainty is a number." },
  { id: 29, title: "FIVE WHYS", description: "Ask why enough times\nand you'll arrive at:\n'we didn't test it.'" },
  { id: 30, title: "FLOW METRICS", description: "Objective proof\nthat the process\nis the bottleneck." },
  { id: 31, title: "HAPPY PATH", description: "The one scenario\neveryone tested.\nUsers take a different one." },
  { id: 32, title: "IMPEDIMENT", description: "What's blocking you\nthat nobody\nhas unblocked yet." },
  { id: 33, title: "INNOVATION SPIKE", description: "Allocated time to explore.\nUsed to catch up\non tech debt instead." },
  { id: 34, title: "ITERATION GOAL", description: "A sentence written\nin planning.\nForgotten by Tuesday standup." },
  { id: 35, title: "KANBAN BOARD", description: "A visual system for moving\ncards from To Do\nto To Do (Later)." },
  { id: 36, title: "KEY RESULT", description: "The metric that proves\nyour objective is working.\nUntil you game it." },
  { id: 37, title: "LEAN COFFEE", description: "A meeting without an agenda\nthat somehow\nfills the full hour." },
  { id: 38, title: "MINIMUM VIABLE PRODUCT", description: "The least you can ship\nbefore stakeholders realize\nit's not what they wanted." },
  { id: 39, title: "MOB PROGRAMMING", description: "Everyone at one keyboard.\nSix opinions per line.\nSurprisingly effective." },
  { id: 40, title: "NONFUNCTIONAL REQS", description: "The things everyone wants\nbut nobody\nputs on the backlog." },
  { id: 41, title: "OKR", description: "An ambitious goal\npaired with a number\nyou'll hit by redefining it." },
  { id: 42, title: "PAIR PROGRAMMING", description: "Two developers, one keyboard.\nOne types. One questions\nthe typing." },
  { id: 43, title: "PARKING LOT", description: "Where good ideas go\nto be acknowledged\nand never revisited." },
  { id: 44, title: "PORTFOLIO KANBAN", description: "A board so high-level\nthat actual work\nis invisible from here." },
  { id: 45, title: "POST-MORTEM", description: "A meeting to learn from failure\nscheduled after\neveryone has moved on." },
  { id: 46, title: "PRODUCT OWNER", description: "Accountable for the backlog,\nthe vision, and\neveryone's frustration." },
  { id: 47, title: "PROGRAM INCREMENT", description: "Twelve weeks of plans\nmade in two days\nbased on vibes." },
  { id: 48, title: "PSYCHOLOGICAL SAFETY", description: "The freedom to fail\nwithout fear.\nCurrently a workshop topic." },
  { id: 49, title: "PULL REQUEST", description: "A request to merge code\nand a forum for opinions\nnobody asked for." },
  { id: 50, title: "RELEASE TRAIN ENGINEER", description: "Conductor of the ART.\nAlso the first to know\nabout the outage." },
  { id: 51, title: "RUBBER DUCK DEBUGGING", description: "Explain your problem\nto an inanimate object\nuntil you solve it yourself." },
  { id: 52, title: "SCRUM OF SCRUMS", description: "A standup for standups.\nMeta enough to feel\nlike progress." },
  { id: 53, title: "SCRUM MASTER", description: "The servant-leader\nwho removes impediments\nthe team put there." },
  { id: 54, title: "SHIFT LEFT TESTING", description: "Finding bugs earlier\nso you have more time\nto argue about them." },
  { id: 55, title: "SOLUTION ARCHITECT", description: "Draws boxes and arrows.\nOwns the decisions\nyou'll regret in six months." },
  { id: 56, title: "SPIKE", description: "Dedicated time to learn\nbefore you estimate.\nOften skipped to save time." },
  { id: 57, title: "SPRINT REVIEW", description: "Show and tell for adults.\nStakeholders show up,\nsee the wrong thing, leave." },
  { id: 58, title: "STAKEHOLDER", description: "Anyone with an opinion\nabout your roadmap\nwho doesn't write code." },
  { id: 59, title: "SYSTEM DEMO", description: "The moment all teams\ndemo to an audience\nof three and a dog." },
  { id: 60, title: "TEAM AGREEMENT", description: "The norms you wrote together\non day one.\nCurrently in a Google Doc." },
  { id: 61, title: "TECHNICAL EXCELLENCE", description: "The thing everyone agrees\nis important\nbut nobody funds." },
  { id: 62, title: "TEST-DRIVEN DEVELOPMENT", description: "Write the test first.\nWatch it fail. Write code.\nRepeat. Feel smug." },
  { id: 63, title: "THREE AMIGOS", description: "Dev, QA, and PO walk in.\nAll leave\nwith different stories." },
  { id: 64, title: "TIMEBOXING", description: "Agreeing in advance\nthat you'll stop,\nwhether or not you're done." },
  { id: 65, title: "USER STORY", description: "As a user, I want\nwhat I asked for,\nso that I get something else." },
  { id: 66, title: "VALUE STREAM", description: "From idea to customer.\nSomewhere in the middle:\na Jira ticket." },
  { id: 67, title: "VELOCITY TRAP", description: "When your metric\nbecomes the goal\nand the goal breaks the metric." },
  { id: 68, title: "WSJF", description: "A formula for prioritization\nthat validates\nwhat you planned anyway." },
  { id: 69, title: "CODE REVIEW", description: "Collegial feedback\nthat takes three days\nand blocks the release." },
  { id: 70, title: "REFACTORING", description: "Improving code\nwithout adding features.\nScheduled for next sprint. Always." },
  { id: 71, title: "DEFINITION OF READY", description: "The checklist a story needs\nbefore it enters the sprint\nand gets stuck." },
  { id: 72, title: "AGILE MANIFESTO", description: "Four values.\nTwelve principles.\nPosted in every non-agile org." },
  { id: 73, title: "WORKING AGREEMENT", description: "Rules the team made\nin a moment of optimism.\nNow laminated." },
  { id: 74, title: "CEREMONY", description: "A meeting with a better name\nso people\nactually show up." },
  { id: 75, title: "CYCLE TIME", description: "How long from start to done.\nLonger than you think.\nShorter than lead time." },
  { id: 76, title: "WIP LIMIT", description: "Maximum work in progress.\nCurrently set to:\nunlimited." },
  { id: 77, title: "ESCAPED DEFECT", description: "A bug that made it\nto production.\nNow it's a 'known issue.'" },
  { id: 78, title: "LEAD TIME", description: "Time from request\nto delivery.\nA number stakeholders resent." },
  { id: 79, title: "THROUGHPUT", description: "Items completed per sprint.\nGoes up when you define\n'completed' loosely." },
  { id: 80, title: "IMPOSTER SYNDROME", description: "The nagging feeling\nyou're the only one\nwho doesn't know what's happening." },
  { id: 81, title: "SCOPE CREEP", description: "Starts with one small ask.\nEnds with a feature\nnobody put in the sprint." },
  { id: 82, title: "PIZZA FRIDAY", description: "The ancient ritual\nof using carbs\nto simulate team bonding." },
  { id: 83, title: "OFFICE DOG", description: "The only attendee\nwho adds value\nto every meeting." },
  { id: 84, title: "THE SNACK BUDGET", description: "Quarterly allocation for morale.\nSpent entirely\nduring PI planning week." },
  { id: 85, title: "OPEN FLOOR PLAN", description: "Designed for collaboration.\nOptimized for\noverhearing everything." },
  { id: 86, title: "HOT TAKE", description: "An unpopular opinion\nshared confidently in retro\nand never followed up on." },
  { id: 87, title: "LAPTOP STICKERS", description: "A curated identity statement.\nPeeled off carefully\nbefore the client visit." },
  { id: 88, title: "SLACK STATUS", description: "Set to 'In a meeting'\nwhile also in Slack\nreplying to this message." },
  { id: 89, title: "THE GROUP CHAT", description: "Where decisions go\nto be made, unmade,\nand remade at 11pm." },
  { id: 90, title: "MEME REVIEW", description: "Unofficial team ceremony.\nAgenda: one Slack thread.\nAttendance: mandatory." },
  { id: 91, title: "MONDAY MORNING", description: "The ceremony before\nthe ceremonies.\nRites include: coffee and sighing." },
  { id: 92, title: "LUNCH ROULETTE", description: "A forced encounter\nwith someone from a team\nyou've only ever pinged." },
  { id: 93, title: "COFFEE MACHINE", description: "The distributed system\nthat determines\nwho actually knows what." },
  { id: 94, title: "UNRELIABLE WIFI", description: "The external dependency\nthat derails the demo\nevery. single. time." },
  { id: 95, title: "WATER COOLER CHAT", description: "The agenda-free meeting\nwhere the real decisions\nactually get made." },
  { id: 96, title: "MEETING ROOM POLITICS", description: "A finite resource allocated\nby the loudest\nor the first invite sent." },
  { id: 97, title: "THE FROZEN LAPTOP", description: "An unplanned spike\ninitiated by IT\nat the worst possible moment." },
  { id: 98, title: "FRIDAY DEPLOY", description: "A calculated risk.\nAlso known as:\n'see you all on Monday.'" },
  { id: 99, title: "SCREEN SHARE CHAOS", description: "The three-minute ritual\nof finding the right window\nbefore everyone gives up." },
  { id: 100, title: "THE ZOOM BACKGROUND", description: "A carefully chosen setting\nthat says 'I am definitely\nsitting at a desk.'" },
  { id: 101, title: "OUT OF OFFICE", description: "A boundary set with care.\nRespected\nby absolutely no one." },
];

module.exports = { opinionCards, cultureCards };
